data:
  forward_window: 24
  symbol: BTC/USDT
  threshold_pct: 0.005
  timeframes:
  - 1h
experiment_name: gru_optimized
model:
  batch_size: 32
  dropout: 0.2975182385457563
  epochs: 50
  hidden_size: 128
  learning_rate: 0.0011103647313054626
  num_layers: 1
  patience: 10
  seq_len: 96
model_type: gru
output:
  model_path: models/gru_v1_optimized.pt
