data:
  forward_window: 24
  symbol: BTC/USDT
  threshold_pct: 0.005
  timeframes:
  - 1h
experiment_name: lightgbm_optimized
model:
  learning_rate: 0.04147864017035564
  max_depth: 7
  n_estimators: 425
  num_leaves: 28
  scale_pos_weight: 1.0580210043606346
model_type: lightgbm
output:
  model_path: models/lightgbm_v1_optimized.pkl
